### ISSUE TITLE
Compile fails on RHEL5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [beagle-dev/beagle-lib#25]
```
I am working from the subversion trunk trying to compile on RHEL5 (gcc 4.1.2, 
autoconf 2.59, libtool 1.5.22) using release 3.1 of the CUDA toolkit.

After running autogen.sh and configure (and then fixing a cuda include 
directory issue in the Makefile's CFLAGS setting), the make crashes out at:

 g++ -DHAVE_CONFIG_H -I. -I. -I../../libhmsbeagle -I/home/lovan/build/beagle-lib/beagle-lib-read-only/libhmsbeagle/GPU/../../. -I/home/lovan/build/beagle-lib/beagle-lib-read-only/libhmsbeagle/GPU/../.. -I/usr/java/default/include -I/usr/java/default/include/linux -msse2 -I/usr/local/cuda/include -O2 -MT libhmsbeagle_cuda_la-GPUInterfaceCUDA.lo -MD -MP -MF .deps/libhmsbeagle_cuda_la-GPUInterfaceCUDA.Tpo -c GPUInterfaceCUDA.cpp  -fPIC -DPIC -o .libs/libhmsbeagle_cuda_la-GPUInterfaceCUDA.o
GPUInterfaceCUDA.cpp: In constructor 'GPUInterface::GPUInterface()':
GPUInterfaceCUDA.cpp:67: warning: converting to non-pointer type 'CUdevice' 
from NULL
GPUInterfaceCUDA.cpp: In member function 'void 
GPUInterface::InitializeKernelMap()':
GPUInterfaceCUDA.cpp:153: error: 'KERNELS_STRING_4' was not declared in this 
scope
GPUInterfaceCUDA.cpp:164: error: 'KERNELS_STRING_16' was not declared in this 
scope
GPUInterfaceCUDA.cpp:175: error: 'KERNELS_STRING_32' was not declared in this 
scope
GPUInterfaceCUDA.cpp:186: error: 'KERNELS_STRING_48' was not declared in this 
scope
GPUInterfaceCUDA.cpp:197: error: 'KERNELS_STRING_64' was not declared in this 
scope
GPUInterfaceCUDA.cpp:208: error: 'KERNELS_STRING_128' was not declared in this 
scope
GPUInterfaceCUDA.cpp:219: error: 'KERNELS_STRING_192' was not declared in this 
scope
make[5]: *** [libhmsbeagle_cuda_la-GPUInterfaceCUDA.lo] Error 1

I suspect that the problem is in building the BeagleCUDA_kernels.h file as 
after being "built" that file only contains one comment line.  If I go down add 
$CUDADIR/include to $INCLUDES in that Makefile, then the include file is built.



```

Original issue reported on code.google.com by `Shea.A.L...@gmail.com` on 10 Aug 2010 at 11:40
